# Site settings
title: Tony  # Your Title
tagline: test  # A brief tagline for your site
sidebar_image: /images/cover.jpg

encoding: UTF-8
markdown: kramdown

paginate: 8
paginate_path: "page:num"

#pygments: true
baseurl: "/test-prj/"
url: "http://ahnjinwoo.github.io"

# Site settings
name:           Tony
email:          
uri:            http://ahnjinwoo.github.io
github:         ahnjinwoo